### ISSUE TITLE
Missing EndCameraRendering and EndFrameRendering in every SPR?

### ISSUE THREAD

**Issue by RadioBear** [cinight/CustomSRP#2]
Hi,
I'm newer with SPR. Is RenderPipeline.BeginFrameRendering and RenderPipeline.BeginCameraRendering should pair call with RenderPipeline.EndFrameRendering and RenderPipeline.EndCameraRendering?

**Comment by cinight** [comment]
thanks a lot! fixed in master branch (2019.3) - dfba8ada32b4b916aedf320cde01d53957538f13
